### ISSUE TITLE
Clarify the LICENSE

### ISSUE THREAD

**Issue by luzpaz** [MariwanJ/COIN3D_Examples#3]
These files are released under coin so what license is that? GPL ? LGPL?

**Comment by MariwanJ** [comment]
Hi @luzpaz , 
You are better than me in that. 
But the folder has not got it's own license and the folder is under 

https://github.com/coin3d/pivy
you find a license file there. 
Please read that and suggest the file or upload it thanks.

**Comment by MariwanJ** [comment]
For my part, it will be the same as FreeCAD, Design456
